### ISSUE TITLE
Installation on RHEL 7

### ISSUE THREAD

**Issue by jamal22066** [benbalter/word-to-markdown-demo#7]
I am getting the following error:

[root@EPSS-CMS-RENDER script]# sh server
which: no growlnotify in (/usr/local/rvm/gems/ruby-2.2.5/bin:/usr/local/rvm/gems/ruby-2.2.5@global/bin:/usr/local/rvm/rubies/ruby-2.2.5/bin:/usr/local/rvm/bin:/sbin:/bin:/usr/sbin:/usr/bin)
which: no terminal-notifier in (/usr/local/rvm/gems/ruby-2.2.5/bin:/usr/local/rvm/gems/ruby-2.2.5@global/bin:/usr/local/rvm/rubies/ruby-2.2.5/bin:/usr/local/rvm/bin:/sbin:/bin:/usr/sbin:/usr/bin)
which: no growlnotify in (/usr/local/rvm/gems/ruby-2.2.5/bin:/usr/local/rvm/gems/ruby-2.2.5@global/bin:/usr/local/rvm/rubies/ruby-2.2.5/bin:/usr/local/rvm/bin:/sbin:/bin:/usr/sbin:/usr/bin)
which: no terminal-notifier in (/usr/local/rvm/gems/ruby-2.2.5/bin:/usr/local/rvm/gems/ruby-2.2.5@global/bin:/usr/local/rvm/rubies/ruby-2.2.5/bin:/usr/local/rvm/bin:/sbin:/bin:/usr/sbin:/usr/bin)

12:41:16 [rerun] Script launched
12:41:16 [rerun] Rerun (11383) running Script (11396)
configuration /var/www/html/word-to-markdown-demo/script/config.ru not found
which: no growlnotify in (/usr/local/rvm/gems/ruby-2.2.5/bin:/usr/local/rvm/gems/ruby-2.2.5@global/bin:/usr/local/rvm/rubies/ruby-2.2.5/bin:/usr/local/rvm/bin:/sbin:/bin:/usr/sbin:/usr/bin)
which: no terminal-notifier in (/usr/local/rvm/gems/ruby-2.2.5/bin:/usr/local/rvm/gems/ruby-2.2.5@global/bin:/usr/local/rvm/rubies/ruby-2.2.5/bin:/usr/local/rvm/bin:/sbin:/bin:/usr/sbin:/usr/bin)
which: no growlnotify in (/usr/local/rvm/gems/ruby-2.2.5/bin:/usr/local/rvm/gems/ruby-2.2.5@global/bin:/usr/local/rvm/rubies/ruby-2.2.5/bin:/usr/local/rvm/bin:/sbin:/bin:/usr/sbin:/usr/bin)
which: no terminal-notifier in (/usr/local/rvm/gems/ruby-2.2.5/bin:/usr/local/rvm/gems/ruby-2.2.5@global/bin:/usr/local/rvm/rubies/ruby-2.2.5/bin:/usr/local/rvm/bin:/sbin:/bin:/usr/sbin:/usr/bin)

12:41:18 [rerun] Script Launch Failed
12:41:18 [rerun] Watching . for **/*.{rb,js,coffee,css,scss,sass,erb,html,haml,ru,yml,slim,md,feature,c,h} with Linux adapter

Any idea what may be causing this? Is there any documentation on how to get this running on a RHEL/CentOS server?

**Comment by benbalter** [comment]
It looks like it's trying to call `growlnotify` which doesn't exist in your path? That's not part of this package.

**Comment by jamal22066** [comment]
I believe the actual error in the above output is:

configuration /var/www/html/word-to-markdown-demo/script/config.ru not found

However, the config.ru file exists in word-to-markdown-demo/config.ru and not in word-to-markdown-demo/script/config.ru. If I copy the file to the script folder, I get the following error:

10:59:20 [rerun] Rerun (25620) running Script (25635)
/var/www/html/word-to-markdown-demo/script/config.ru:1:in `require': cannot load such file -- ./server (LoadError)
        from /var/www/html/word-to-markdown-demo/script/config.ru:1:in `block in <main>'
        from /usr/local/rvm/gems/ruby-2.2.5/gems/rack-2.0.4/lib/rack/builder.rb:55:in `instance_eval'
        from /usr/local/rvm/gems/ruby-2.2.5/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
        from /var/www/html/word-to-markdown-demo/script/config.ru:in `new'
        from /var/www/html/word-to-markdown-demo/script/config.ru:in `<main>'
        from /usr/local/rvm/gems/ruby-2.2.5/gems/rack-2.0.4/lib/rack/builder.rb:49:in `eval'
        from /usr/local/rvm/gems/ruby-2.2.5/gems/rack-2.0.4/lib/rack/builder.rb:49:in `new_from_string'
        from /usr/local/rvm/gems/ruby-2.2.5/gems/rack-2.0.4/lib/rack/builder.rb:40:in `parse_file'
        from /usr/local/rvm/gems/ruby-2.2.5/gems/rack-2.0.4/lib/rack/server.rb:319:in `build_app_and_options_from_config'
        from /usr/local/rvm/gems/ruby-2.2.5/gems/rack-2.0.4/lib/rack/server.rb:219:in `app'
        from /usr/local/rvm/gems/ruby-2.2.5/gems/rack-2.0.4/lib/rack/server.rb:354:in `wrapped_app'
        from /usr/local/rvm/gems/ruby-2.2.5/gems/rack-2.0.4/lib/rack/server.rb:283:in `start'
        from /usr/local/rvm/gems/ruby-2.2.5/gems/rack-2.0.4/lib/rack/server.rb:148:in `start'
        from /usr/local/rvm/gems/ruby-2.2.5/gems/rack-2.0.4/bin/rackup:4:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.5/bin/rackup:23:in `load'
        from /usr/local/rvm/gems/ruby-2.2.5/bin/rackup:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `<main>'

10:59:23 [rerun] Script Launch Failed

Would you be able to shed any light on why this is looking for a file that is not in the right location according to your code? I *believe* that is where the failure is happening.

**Comment by benbalter** [comment]
@jamal22066 what command are you running to generate this output? It looks like you're running `server` while in the script directory? `script/server` should be run from the repo root, or you can run `bundle exec rerun rackup` directly.

**Comment by jamal22066** [comment]
OK, that was pretty stupid of me. It is working now:

[root@EPSS-CMS-RENDER word-to-markdown-demo]# netstat -tnlp | grep 9292
tcp        0      0 127.0.0.1:9292          0.0.0.0:*               LISTEN      1686/ruby /usr/loca
tcp6       0      0 ::1:9292                :::*                    LISTEN      1686/ruby /usr/loca

Sorry for the trouble and thank you for creating this!

**Comment by jamal22066** [comment]
hi Ben, 

One additional question, this is meant to work from localhost:9292. Do you know of a way I can change this to listen from 0.0.0.0:9292 or serverip:9292 instead of 127.0.0.1:9292? I am running Nodejs. Not sure if this would be a nodejs change or something in the software config files can be changed to get this listen to the server IP so that the software is available for all users when installed on a server and not just localhost.

**Comment by jamal22066** [comment]
Fixed. Got this listening on the server IP instead of 127.0.0.1
